spring.application.name=local-review-platform

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/local_review}
spring.datasource.username=${DB_USERNAME:ysh}
spring.datasource.password=${DB_PASSWORD:}

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.timeout=${REDIS_TIMEOUT:2s}

app.auth.token-ttl=${TOKEN_TTL:30m}
app.auth.code-ttl=${CODE_TTL:5m}
app.stream.order-key=${ORDER_STREAM_KEY:stream.orders}
app.stream.order-group=${ORDER_STREAM_GROUP:order-group}
app.stream.max-retries=${ORDER_STREAM_MAX_RETRIES:3}
