import { FormEvent, useCallback, useEffect, useState } from 'react'
import { api, ApiError } from './api'
import type { Brand, MyVoucher, Page, Promotion, Store, User } from './types'

type View = 'consumer' | 'my' | 'merchant'
type LoginMode = 'USER' | 'MERCHANT'
const errors: Record<string,string> = { FORBIDDEN:'当前账号没有商户操作权限', OUT_OF_STOCK:'活动已抢完', DUPLICATE_ORDER:'你已经领取过该优惠券', INVALID_CODE:'验证码错误或已过期', INVALID_PHONE:'请输入正确的手机号' }
const messageOf = (e: unknown) => e instanceof ApiError ? (errors[e.code] || e.message) : '操作失败，请稍后重试'
const statusText = (s: string) => ({ACTIVE:'进行中',SOLD_OUT:'已抢完',SCHEDULED:'未开始',ENDED:'已结束'}[s] || s)
const formatDateTime = (value: string) => value.replace('T',' ').slice(0,16)
const formatDistance = (value?: number) => value == null ? '' : value < 1 ? `${Math.round(value*1000)} m` : `${value.toFixed(1)} km`

export default function App() {
  const [user,setUser]=useState<User|null>(null), [phone,setPhone]=useState(''), [code,setCode]=useState('')
  const [mode,setMode]=useState<LoginMode>('USER'), [notice,setNotice]=useState(''), [loading,setLoading]=useState(false), [view,setView]=useState<View>('consumer')
  const restore=useCallback(async()=>{ if(!localStorage.getItem('token')) return; try { const u=await api<User>('/user/me'); setUser(u); setView(u.role==='MERCHANT'?'merchant':'consumer') } catch { localStorage.removeItem('token') } },[])
  useEffect(()=>{void restore()},[restore])
  async function sendCode(){setLoading(true);setNotice('');try{await api(`/user/code?phone=${encodeURIComponent(phone)}`,{method:'POST'});setNotice('验证码已发送（本地演示验证码：123456）')}catch(e){setNotice(messageOf(e))}finally{setLoading(false)}}
  async function login(e:FormEvent){e.preventDefault();setLoading(true);setNotice('');try{const r=await api<{token:string}>('/user/login',{method:'POST',body:JSON.stringify({phone,code,loginMode:mode})});localStorage.setItem('token',r.token);const u=await api<User>('/user/me');setUser(u);setView(mode==='MERCHANT'?'merchant':'consumer')}catch(err){localStorage.removeItem('token');setNotice(messageOf(err))}finally{setLoading(false)}}
  function logout(){localStorage.removeItem('token');setUser(null);setNotice('已退出登录')}
  if(!user)return <main className="auth-shell"><section className="login-card"><p className="eyebrow">本地门店营销平台</p><h1>发现附近好店<br/>体验限时优惠</h1><p className="muted">连接真实后端、库存与订单的本地演示系统。</p>
    <div className="login-mode" role="tablist" aria-label="登录方式"><button type="button" role="tab" aria-selected={mode==='USER'} className={mode==='USER'?'active':'secondary'} onClick={()=>{setMode('USER');setNotice('')}}>用户登录</button><button type="button" role="tab" aria-selected={mode==='MERCHANT'} className={mode==='MERCHANT'?'active':'secondary'} onClick={()=>{setMode('MERCHANT');setNotice('')}}>商户登录</button></div>
    <form onSubmit={login}><label>手机号<input aria-label="手机号" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>验证码<div className="inline"><input aria-label="验证码" value={code} onChange={e=>setCode(e.target.value)}/><button type="button" className="secondary" onClick={sendCode}>获取验证码</button></div></label><button disabled={loading}>{loading?'正在登录…':`进入${mode==='MERCHANT'?'商户后台':'发现'}`}</button></form>{notice&&<p className="notice">{notice}</p>}</section></main>
  return <div><header><div><p className="eyebrow">本地门店营销平台</p><strong>门店优惠</strong></div><nav><button className={view==='consumer'?'active':'ghost'} onClick={()=>setView('consumer')}>发现</button><button className={view==='my'?'active':'ghost'} onClick={()=>setView('my')}>我的优惠券</button>{user.role==='MERCHANT'&&<button className={view==='merchant'?'active':'ghost'} onClick={()=>setView('merchant')}>商户后台</button>}</nav><div className="user"><span>{user.nickname}</span><small>{user.phone} · {user.role}</small><button className="ghost" onClick={logout}>退出登录</button></div></header>{view==='consumer'?<Consumer/>:view==='my'?<My/>:user.role==='MERCHANT'?<Merchant/>:<Consumer/>}</div>
}

function Consumer(){
  const [stores,setStores]=useState<Store[]>([]),[selected,setSelected]=useState<Store|null>(null),[promos,setPromos]=useState<Promotion[]>([]),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[nearby,setNearby]=useState(false)
  const loadAll=useCallback(async()=>{setLoading(true);setNotice('');try{setStores((await api<Page<Store>>('/businesses?size=50')).content);setNearby(false)}catch(e){setNotice(messageOf(e))}finally{setLoading(false)}},[])
  useEffect(()=>{void loadAll()},[loadAll])
  async function loadNearby(longitude:number,latitude:number,label:string){setLoading(true);setNotice('');try{setStores(await api(`/businesses/nearby?longitude=${longitude}&latitude=${latitude}&radius=50`));setNearby(true);setNotice(`正在使用${label}，结果按距离由近到远排列。`)}catch(e){setNotice(messageOf(e))}finally{setLoading(false)}}
  function requestLocation(){if(!navigator.geolocation){setNotice('当前浏览器不支持定位，可使用测试位置查看附近门店。');return}setLoading(true);navigator.geolocation.getCurrentPosition(p=>void loadNearby(p.coords.longitude,p.coords.latitude,'当前位置'),()=>{setLoading(false);setNotice('无法获取当前位置，可使用测试位置查看附近门店。')},{timeout:5000})}
  async function open(s:Store){setNotice('');try{const[d,p]=await Promise.all([api<Store>(`/businesses/${s.id}`),api<Promotion[]>(`/stores/${s.id}/vouchers`)]);setSelected(d);setPromos(p)}catch(e){setNotice(messageOf(e))}}
  async function buy(id:number){setNotice('正在提交请求…');try{const r=await api<{status:string}>(`/voucher/seckill/${id}`,{method:'POST'});if(selected)await open(selected);setNotice(r.status==='PROCESSING'?'请求已受理，正在处理中，可前往「我的优惠券」查看结果。':`请求状态：${r.status}`)}catch(e){setNotice(messageOf(e))}}
  return <main><section className="hero"><p className="eyebrow">发现好店</p><h1>附近门店与限时优惠</h1><p>门店、库存和订单结果均来自真实运行的后端服务。</p><div className="discovery-actions"><button className={!nearby?'active':'secondary'} onClick={()=>void loadAll()}>全部门店</button><button className={nearby?'active':'secondary'} onClick={requestLocation}>查看附近门店</button><button className="ghost" onClick={()=>void loadNearby(121.4737,31.2304,'上海市中心测试位置')}>使用测试位置</button></div><small>测试位置仅用于本地演示 Redis GEO，不代表你的真实位置。</small></section>{notice&&<p className="notice">{notice}</p>}{loading?<p>正在加载门店…</p>:<div className="grid">{stores.map(s=><article className="card" key={s.id} onClick={()=>open(s)}><span className="badge">{s.brandName||'独立门店'}</span>{s.distance!=null&&<span className="distance">距你 {formatDistance(s.distance)}</span>}<h2>{s.name}</h2><p>{s.category} · {s.rating==null?'暂无评分':`★ ${s.rating} 分`}</p><p className="muted">{s.address}</p></article>)}</div>}{selected&&<section className="detail"><button className="ghost" onClick={()=>setSelected(null)}>关闭</button><h2>{selected.name}</h2><p>{selected.address}</p><h3>当前营销活动</h3>{promos.length?promos.map(p=><div className="promotion" key={p.id}><div><strong>{p.title}</strong><p>{statusText(p.status)} · 剩余 {p.stock} 份 · 已领取 {p.orderCount} 份</p></div><button disabled={p.status!=='ACTIVE'} onClick={()=>buy(p.id)}>{p.status==='ACTIVE'?'立即抢购':statusText(p.status)}</button></div>):<p className="muted">暂无营销活动</p>}</section>}</main>
}

function My(){
  const [items,setItems]=useState<MyVoucher[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{setItems(await api('/me/vouchers'))}catch(e){setError(messageOf(e))}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load])
  return <main><section className="hero"><p className="eyebrow">个人中心</p><h1>我的优惠券</h1><p>这里展示已经成功写入订单的优惠券。</p><button className="secondary" onClick={()=>load()}>刷新</button></section>{error&&<p className="notice">{error}</p>}{loading?<p>正在加载优惠券…</p>:items.length?<div className="grid">{items.map(v=><article className="card" key={v.orderId}><span className="badge">{v.status==='AVAILABLE'?'可使用':'已过期'}</span><h2>{v.voucherTitle}</h2><p>{v.storeName}</p><p className="muted">有效期至 {formatDateTime(v.endTime)}</p></article>)}</div>:<p className="muted">暂无优惠券</p>}</main>
}

function Merchant(){
  const [brands,setBrands]=useState<Brand[]>([]),[stores,setStores]=useState<Store[]>([]),[selectedId,setSelectedId]=useState<number|null>(null),[promos,setPromos]=useState<Promotion[]>([]),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[editingId,setEditingId]=useState<number|null>(null),[editName,setEditName]=useState('')
  const refresh=useCallback(async()=>{setLoading(true);try{const[b,s]=await Promise.all([api<Brand[]>('/brands'),api<Page<Store>>('/businesses?size=50')]);setBrands(b);setStores(s.content)}catch(e){setNotice(messageOf(e))}finally{setLoading(false)}},[]);useEffect(()=>{void refresh()},[refresh])
  async function loadPromos(id:number){setSelectedId(id);try{setPromos(await api(`/stores/${id}/vouchers`))}catch(e){setNotice(messageOf(e))}}
  async function createBrand(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);try{await api('/brands',{method:'POST',body:JSON.stringify({name:d.get('name'),description:d.get('description')})});f.reset();setNotice('品牌创建成功');await refresh()}catch(err){setNotice(messageOf(err))}}
  async function createStore(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);try{await api('/businesses',{method:'POST',body:JSON.stringify({name:d.get('name'),category:d.get('category'),address:d.get('address'),longitude:Number(d.get('longitude')),latitude:Number(d.get('latitude')),brandId:Number(d.get('brandId'))||null})});f.reset();setNotice('门店创建成功');await refresh()}catch(err){setNotice(messageOf(err))}}
  async function save(id:number){if(!editName.trim())return;try{await api(`/businesses/${id}`,{method:'PUT',body:JSON.stringify({name:editName.trim()})});setEditingId(null);setNotice('门店信息已更新');await refresh()}catch(e){setNotice(messageOf(e))}}
  async function createPromo(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedId)return;const f=e.currentTarget,d=new FormData(f);try{await api(`/stores/${selectedId}/vouchers`,{method:'POST',body:JSON.stringify({title:d.get('title'),stock:Number(d.get('stock')),beginTime:d.get('beginTime'),endTime:d.get('endTime')})});f.reset();setNotice('营销活动创建成功');await loadPromos(selectedId)}catch(err){setNotice(messageOf(err))}}
  async function deleteStore(id:number){if(!window.confirm('确定删除该门店吗？'))return;try{await api(`/businesses/${id}`,{method:'DELETE'});if(selectedId===id){setSelectedId(null);setPromos([])}setNotice('门店已删除');await refresh()}catch(e){setNotice(messageOf(e))}}
  async function closeStore(id:number){if(!window.confirm('关闭后用户将无法发现门店或领取优惠券，确定继续吗？'))return;try{await api(`/businesses/${id}/close`,{method:'POST'});setNotice('门店已关闭');await refresh()}catch(e){setNotice(messageOf(e))}}
  async function deletePromo(id:number){if(!window.confirm('确定删除该营销活动吗？'))return;try{await api(`/vouchers/${id}`,{method:'DELETE'});setNotice('营销活动已删除');if(selectedId)await loadPromos(selectedId)}catch(e){setNotice(messageOf(e))}}
  const selectedStore=stores.find(s=>s.id===selectedId)
  return <main><section className="hero"><p className="eyebrow">商户管理</p><h1>商户后台</h1><p>管理品牌、门店和限时营销活动，查看实时库存与订单数量。</p></section>{notice&&<p className="notice">{notice}</p>}<div className="console-grid"><section className="panel"><h2>创建品牌</h2><form onSubmit={createBrand}><input name="name" placeholder="品牌名称" required/><input name="description" placeholder="品牌简介"/><button>创建品牌</button></form><h2>创建门店</h2><form onSubmit={createStore}><input name="name" placeholder="门店名称" required/><input name="category" placeholder="经营品类" required/><input name="address" placeholder="门店地址" required/><label>纬度<input name="latitude" type="number" step="any" defaultValue="31.2304" required/></label><label>经度<input name="longitude" type="number" step="any" defaultValue="121.4737" required/></label><small>默认值为上海市中心测试坐标，仅用于本地 GEO 演示。</small><select name="brandId"><option value="">独立门店</option>{brands.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select><button>创建门店</button></form></section><section className="panel"><h2>门店列表</h2>{loading?<p>正在加载…</p>:stores.map(s=><div className="row" key={s.id}>{editingId===s.id?<><input aria-label="编辑门店名称" value={editName} onChange={e=>setEditName(e.target.value)}/><button onClick={()=>save(s.id)}>保存</button></>:<><button className="link" onClick={()=>loadPromos(s.id)}>{s.name}<small>{s.status==='CLOSED'?'已关闭':(s.brandName||'独立门店')} · {s.address} · {s.rating==null?'暂无评分':`${s.rating} 分`}</small></button><button className="ghost" onClick={()=>{setEditingId(s.id);setEditName(s.name)}}>编辑</button>{s.status==='ACTIVE'&&<button className="ghost" onClick={()=>closeStore(s.id)}>关闭门店</button>}<button className="danger" onClick={()=>deleteStore(s.id)}>删除门店</button></>}</div>)}</section><section className="panel"><h2>营销活动</h2>{selectedId?<>{selectedStore?.status==='ACTIVE'?<form onSubmit={createPromo}><input name="title" placeholder="活动名称" required/><input name="stock" type="number" min="0" placeholder="库存数量" required/><label>开始时间<input name="beginTime" type="datetime-local" required/></label><label>结束时间<input name="endTime" type="datetime-local" required/></label><button>创建营销活动</button></form>:<p className="notice">门店已关闭，不能创建新的营销活动</p>}{promos.map(p=><div className="promotion" key={p.id}><div><strong>{p.title}</strong><p>{statusText(p.status)}</p></div><div><b>{p.stock}</b> 份剩余<br/><small>{p.orderCount} 份已领取</small><br/><button className="danger" onClick={()=>deletePromo(p.id)}>删除活动</button></div></div>)}</>:<p className="muted">请先选择门店</p>}</section></div></main>
}
